{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatFormConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFormConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatsdk\/chatformconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/chatformconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatSDK\/SQ","doc:\/\/com.zendesk.ChatSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration object used to gather the desired requirements for a Chat form."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFormConfiguration"}],"title":"ChatFormConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration","modules":[{"name":"ChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChatFormConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/init(name:email:phoneNumber:department:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/debugDescription","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/department","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/description","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/email","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/name","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/phoneNumber"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/isEqual(_:)"]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/phoneNumber":{"role":"symbol","title":"phoneNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}],"abstract":[{"type":"text","text":"Sets how the phone number field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/phoneNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneNumber"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/phonenumber"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/description"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/init(name:email:phoneNumber:department:)":{"role":"symbol","title":"init(name:email:phoneNumber:department:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"department"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/init(name:email:phoneNumber:department:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:email:phoneNumber:department:"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/init(name:email:phonenumber:department:)"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"role":"symbol","title":"ChatFormConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFormConfiguration"}],"abstract":[{"type":"text","text":"Configuration object used to gather the desired requirements for a Chat form."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatFormConfiguration"}],"url":"\/documentation\/chatsdk\/chatformconfiguration"},"doc://com.zendesk.ChatSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/department":{"role":"symbol","title":"department","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"department"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}],"abstract":[{"type":"text","text":"Sets how the department selection field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/department","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"department"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/department"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/isequal(_:)"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/email":{"role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}],"abstract":[{"type":"text","text":"Sets how the email field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/email","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"email"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/email"},"doc://com.zendesk.ChatSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ChatSDK\/s7CVarArgP"},"doc://com.zendesk.ChatSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SH"},"doc://com.zendesk.ChatSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"},"doc://com.zendesk.ChatSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ChatSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/debugDescription":{"role":"symbol","title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/debugDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/debugdescription"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}],"abstract":[{"type":"text","text":"Sets how the name field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/name"},"doc://com.zendesk.ChatSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatSDK\/objc(pl)NSObject"},"doc://com.zendesk.ChatSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SQ"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","title":"ChatSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatFormConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/debugDescription","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/department","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/description","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/email","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/name","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/phoneNumber"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/init(name:email:phoneNumber:department:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKChatFormConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1phoneNumber\/title","value":"phoneNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1phoneNumber\/fragments","value":[{"kind":"identifier","text":"phoneNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1init(name:email:phoneNumber:department:)\/title","value":"initWithName:email:phoneNumber:department:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1init(name:email:phoneNumber:department:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:email:phoneNumber:department:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title","value":"ZDKChatFormConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1department\/title","value":"department"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1department\/fragments","value":[{"kind":"identifier","text":"department"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1email\/title","value":"email"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1email\/fragments","value":[{"kind":"identifier","text":"email"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1debugDescription\/title","value":"debugDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1debugDescription\/fragments","value":[{"kind":"identifier","text":"debugDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1name\/fragments","value":[{"kind":"identifier","text":"name"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}