{"abstract":[{"type":"text","text":"Inherited from "},{"code":"Loggable.log","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Log","preciseIdentifier":"s:16ChatProvidersSDK3LogP"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"extendedModule":"ChatProvidersSDK","externalID":"s:16ChatProvidersSDK8LoggablePAAE3logAA3Log_pvp::SYNTHESIZED::c:@M@ChatSDK@objc(cs)ZDKChatEngine","roleHeading":"Instance Property","modules":[{"name":"ChatSDK","relatedModules":["ChatProvidersSDK"]}],"symbolKind":"property","title":"log","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"Log","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK3LogP"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine\/log"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/log","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/log":{"kind":"symbol","title":"log","url":"\/documentation\/chatsdk\/chatengine\/log","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Log","preciseIdentifier":"s:16ChatProvidersSDK3LogP"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/log","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"abstract":[{"code":"ChatEngine","type":"codeVoice"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","title":"ChatEngine","type":"topic","url":"\/documentation\/chatsdk\/chatengine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatEngine","kind":"identifier"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ZDKChatEngine","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatEngine"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatEngine"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}