{"kind":"article","topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/addObserver(_:identifier:eagerObserver:onRemove:_:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/notifyObservers(_:)"],"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine\/observable-implementations"]}],"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"ChatSDK"}],"role":"collectionGroup","title":"Observable Implementations"},"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Observable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/addObserver(_:identifier:eagerObserver:onRemove:_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ObservableIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"eagerObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","text":"Observable","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onRemove","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, (","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","text":"Observable","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken","text":"ObservationToken","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/addObserver(_:identifier:eagerObserver:onRemove:_:)","abstract":[],"title":"addObserver(_:identifier:eagerObserver:onRemove:_:)","type":"topic","url":"\/documentation\/chatsdk\/chatengine\/addobserver(_:identifier:eagerobserver:onremove:_:)","kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"abstract":[{"code":"ChatEngine","type":"codeVoice"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","title":"ChatEngine","type":"topic","url":"\/documentation\/chatsdk\/chatengine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatEngine","kind":"identifier"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/notifyObservers(_:)":{"kind":"symbol","abstract":[],"type":"topic","title":"notifyObservers(_:)","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/notifyObservers(_:)","role":"symbol","url":"\/documentation\/chatsdk\/chatengine\/notifyobservers(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyObservers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Observable","preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"ZDKChatEngine","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title","op":"replace"},{"value":[{"text":"ZDKChatEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments","op":"replace"},{"value":[{"text":"ZDKChatEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}