{"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/start(messagingAPI:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messagingAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI0A11APIProtocolP","text":"MessagingAPIProtocol"},{"kind":"text","text":")"}]}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ChatSDK"}],"extendedModule":"ChatSDK","title":"start(messagingAPI:)","symbolKind":"method","externalID":"s:7ChatSDK0A6EngineC5start12messagingAPIy09MessagingF00G11APIProtocol_p_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messagingAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingAPIProtocol","preciseIdentifier":"s:12MessagingAPI0A11APIProtocolP"},{"kind":"text","text":")"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine\/start(messagingapi:)"]}],"abstract":[{"type":"text","text":"Notifies the engine to start taking over the support process."}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/start(messagingAPI:)":{"role":"symbol","kind":"symbol","title":"start(messagingAPI:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messagingAPI","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingAPIProtocol","preciseIdentifier":"s:12MessagingAPI0A11APIProtocolP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Notifies the engine to start taking over the support process."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/start(messagingAPI:)","type":"topic","url":"\/documentation\/chatsdk\/chatengine\/start(messagingapi:)"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"abstract":[{"code":"ChatEngine","type":"codeVoice"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","title":"ChatEngine","type":"topic","url":"\/documentation\/chatsdk\/chatengine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatEngine","kind":"identifier"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title","value":"ZDKChatEngine"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments","value":[{"kind":"identifier","text":"ZDKChatEngine"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatEngine"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}