{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/phonenumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/phonenumber"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"},{"text":": ","kind":"text"},{"text":"FormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"phoneNumber"}],"symbolKind":"property","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration(py)phoneNumber","role":"symbol","modules":[{"name":"ChatSDK"}],"title":"phoneNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"phoneNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/phoneNumber","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets how the phone number field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection","type":"topic","abstract":[],"title":"ChatSDK","url":"\/documentation\/chatsdk"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/phoneNumber":{"role":"symbol","url":"\/documentation\/chatsdk\/chatformconfiguration\/phonenumber","abstract":[{"type":"text","text":"Sets how the phone number field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"navigatorTitle":[{"text":"phoneNumber","kind":"identifier"}],"type":"topic","title":"phoneNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","kind":"typeIdentifier","text":"FormFieldStatus"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/phoneNumber"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"url":"\/documentation\/chatsdk\/chatformconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatFormConfiguration"}],"title":"ChatFormConfiguration","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration object used to gather the desired requirements for a Chat form."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"navigatorTitle":[{"text":"FormFieldStatus","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","abstract":[{"type":"codeVoice","code":"FormFieldStatus"},{"text":" is used to set if a field in the pre-chat or offline- form is","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"required"},{"text":", ","type":"text"},{"type":"codeVoice","code":"optional"},{"text":" or ","type":"text"},{"code":"hidden","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/chatsdk\/formfieldstatus","kind":"symbol","title":"FormFieldStatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FormFieldStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"phoneNumber","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"phoneNumber","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"phoneNumber","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1phoneNumber\/title"},{"value":[{"text":"phoneNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1phoneNumber\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title","op":"replace","value":"ZDKChatFormConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments","value":[{"text":"ZDKChatFormConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title","op":"replace","value":"ZDKFormFieldStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments","value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}