{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreChatFormEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/chatsdk\/chatconfiguration\/isprechatformenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/chatconfiguration\/isprechatformenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isPreChatFormEnabled"},"abstract":[{"type":"text","text":"If TRUE, the pre-chat form will be shown to the user. TRUE by default."}],"metadata":{"symbolKind":"property","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration(py)isPreChatFormEnabled","role":"symbol","title":"isPreChatFormEnabled","navigatorTitle":[{"kind":"identifier","text":"isPreChatFormEnabled"}],"modules":[{"name":"ChatSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreChatFormEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property"},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","navigatorTitle":[{"kind":"identifier","text":"ChatConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConfiguration"}],"title":"ChatConfiguration","role":"symbol","url":"\/documentation\/chatsdk\/chatconfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isPreChatFormEnabled":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isPreChatFormEnabled","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk\/chatconfiguration\/isprechatformenabled","navigatorTitle":[{"kind":"identifier","text":"isPreChatFormEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreChatFormEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","abstract":[{"text":"If TRUE, the pre-chat form will be shown to the user. TRUE by default.","type":"text"}],"title":"isPreChatFormEnabled"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isPreChatFormEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"isPreChatFormEnabled"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isPreChatFormEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKChatConfiguration","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","value":[{"text":"ZDKChatConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isPreChatFormEnabled\/title","value":"isPreChatFormEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isPreChatFormEnabled\/fragments","value":[{"text":"isPreChatFormEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}