{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailTranscript"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatsdk\/chatmenuaction\/emailtranscript"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/chatmenuaction\/emailtranscript"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/emailTranscript","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Allows the user to send a transcript of the finished chat to the specified email"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailTranscript"}],"title":"ChatMenuAction.emailTranscript","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatSDK@E@ZDKChatMenuAction@ZDKChatMenuActionEmailTranscript","modules":[{"name":"ChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatMenuActionEmailTranscript"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction"]]},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction":{"role":"symbol","title":"ChatMenuAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMenuAction"}],"abstract":[{"type":"text","text":"Possible items that appear in the right "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" in the Chat screen’s "},{"type":"codeVoice","code":"UINavigationController"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMenuAction"}],"url":"\/documentation\/chatsdk\/chatmenuaction"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","title":"ChatSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/emailTranscript":{"role":"symbol","title":"ChatMenuAction.emailTranscript","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailTranscript"}],"abstract":[{"type":"text","text":"Allows the user to send a transcript of the finished chat to the specified email"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/emailTranscript","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKChatMenuActionEmailTranscript"}],"url":"\/documentation\/chatsdk\/chatmenuaction\/emailtranscript"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatMenuActionEmailTranscript"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatMenuActionEmailTranscript"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKChatMenuActionEmailTranscript"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/title","value":"ZDKChatMenuAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/fragments","value":[{"kind":"identifier","text":"ZDKChatMenuAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1emailTranscript\/title","value":"ZDKChatMenuActionEmailTranscript"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1emailTranscript\/fragments","value":[{"kind":"identifier","text":"ZDKChatMenuActionEmailTranscript"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}