{"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/hashValue"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/hash(into:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chatsdk\/chatmenuaction\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction"]]},"metadata":{"role":"collectionGroup","title":"RawRepresentable Implementations","modules":[{"name":"ChatSDK"}],"roleHeading":"API Collection"},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/hashValue":{"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"hashValue","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/chatsdk\/chatmenuaction\/hashvalue","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/hashValue"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction":{"type":"topic","title":"ChatMenuAction","url":"\/documentation\/chatsdk\/chatmenuaction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMenuAction"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMenuAction"}],"abstract":[{"type":"text","text":"Possible items that appear in the right "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" in the Chat screen’s "},{"type":"codeVoice","code":"UINavigationController"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/hash(into:)":{"kind":"symbol","role":"symbol","title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/chatsdk\/chatmenuaction\/hash(into:)","abstract":[],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/hash(into:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ZDKChatMenuAction","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatMenuAction"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/fragments"},{"op":"replace","value":[{"text":"ZDKChatMenuAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}