{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"required","kind":"identifier"}]}]}],"metadata":{"externalID":"c:@M@ChatSDK@E@ZDKFormFieldStatus@ZDKFormFieldStatusRequired","modules":[{"name":"ChatSDK"}],"title":"FormFieldStatus.required","navigatorTitle":[{"text":"ZDKFormFieldStatusRequired","kind":"identifier"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/formfieldstatus\/required"]},{"paths":["\/documentation\/chatsdk\/formfieldstatus\/required"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/required","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"]]},"abstract":[{"text":"Field will be shown to end-user with no ","type":"text"},{"type":"codeVoice","code":"skip"},{"type":"text","text":" button."}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/required":{"title":"FormFieldStatus.required","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/required","navigatorTitle":[{"text":"ZDKFormFieldStatusRequired","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatsdk\/formfieldstatus\/required","kind":"symbol","abstract":[{"type":"text","text":"Field will be shown to end-user with no "},{"type":"codeVoice","code":"skip"},{"text":" button.","type":"text"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"kind":"symbol","type":"topic","title":"FormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","role":"symbol","abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"type":"text","text":" is used to set if a field in the pre-chat or offline- form is"},{"type":"text","text":" "},{"type":"codeVoice","code":"required"},{"type":"text","text":", "},{"code":"optional","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"hidden"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormFieldStatus"}],"navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"url":"\/documentation\/chatsdk\/formfieldstatus"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKFormFieldStatusRequired"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"ZDKFormFieldStatusRequired","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKFormFieldStatusRequired","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKFormFieldStatusRequired","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1required\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1required\/fragments","value":[{"text":"ZDKFormFieldStatusRequired","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title","value":"ZDKFormFieldStatus","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}