{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"menuActions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}],"modules":[{"name":"ChatSDK"}],"title":"menuActions","role":"symbol","platforms":[],"roleHeading":"Instance Property","extendedModule":"ChatSDK","externalID":"c:@CM@ChatSDK@objc(cs)ZDKChatConfiguration(py)menuActions","symbolKind":"property","navigatorTitle":[{"text":"menuActions","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatconfiguration\/menuactions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatconfiguration\/menuactions"]}],"sections":[],"abstract":[{"text":"Retrieve the Integer values of the ","type":"text"},{"code":"ChatMenuAction","type":"codeVoice"},{"text":"s applied to the config","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"menuActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/menuActions"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"]]},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","navigatorTitle":[{"text":"ChatConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatsdk\/chatconfiguration","title":"ChatConfiguration","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk","abstract":[],"role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/menuActions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"menuActions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Retrieve the Integer values of the "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s applied to the config"}],"deprecated":true,"title":"menuActions","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/menuActions","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"menuActions","kind":"identifier"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/menuactions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"menuActions","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"menuActions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"menuActions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKChatConfiguration","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title"},{"value":[{"kind":"identifier","text":"ZDKChatConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"ZDKChatConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/navigatorTitle"},{"value":"menuActions","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1menuActions\/title"},{"value":[{"text":"menuActions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1menuActions\/fragments"}]}]}