{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isChatTranscriptPromptEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isChatTranscriptPromptEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isChatTranscriptPromptEnabled"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration(py)isChatTranscriptPromptEnabled","title":"isChatTranscriptPromptEnabled","modules":[{"name":"ChatSDK"}]},"abstract":[{"text":"If TRUE, users are asked if they want to request a chat transcript at the end of the chat. TRUE by default.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatconfiguration\/ischattranscriptpromptenabled"]},{"paths":["\/documentation\/chatsdk\/chatconfiguration\/ischattranscriptpromptenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isChatTranscriptPromptEnabled"},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"type":"topic","navigatorTitle":[{"text":"ChatConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"ChatConfiguration","abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"code":"ChatMenuAction","type":"codeVoice"},{"text":"s","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConfiguration","kind":"identifier"}],"url":"\/documentation\/chatsdk\/chatconfiguration","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isChatTranscriptPromptEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isChatTranscriptPromptEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isChatTranscriptPromptEnabled","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"If TRUE, users are asked if they want to request a chat transcript at the end of the chat. TRUE by default."}],"kind":"symbol","url":"\/documentation\/chatsdk\/chatconfiguration\/ischattranscriptpromptenabled","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isChatTranscriptPromptEnabled","title":"isChatTranscriptPromptEnabled"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"abstract":[],"type":"topic","title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection","url":"\/documentation\/chatsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"isChatTranscriptPromptEnabled","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isChatTranscriptPromptEnabled"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"isChatTranscriptPromptEnabled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title","value":"ZDKChatConfiguration","op":"replace"},{"value":[{"text":"ZDKChatConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isChatTranscriptPromptEnabled\/title","value":"isChatTranscriptPromptEnabled"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isChatTranscriptPromptEnabled\/fragments","value":[{"text":"isChatTranscriptPromptEnabled","kind":"identifier"}],"op":"replace"}]}]}