{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setChatMenuActions","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"actions","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Array of "},{"type":"codeVoice","code":"ChatMenuAction"},{"text":" that are casted to an array of integers.","type":"text"}],"type":"paragraph"}],"name":"actions"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Example:","anchor":"Example"},{"code":["NSArray *update = @[@(ZDKChatMenuActionEmailTranscript),","                    @(ZDKChatMenuActionEndChat)];","","[_config setChatMenuActionsWithActions: update];"],"type":"codeListing","syntax":"objc"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/setChatMenuActions(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"setChatMenuActions:","kind":"identifier"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","platforms":[],"externalID":"c:@CM@ChatSDK@objc(cs)ZDKChatConfiguration(im)setChatMenuActions:","title":"setChatMenuActions(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setChatMenuActions","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"])"}],"modules":[{"name":"ChatSDK"}],"extendedModule":"ChatSDK"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatconfiguration\/setchatmenuactions(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatconfiguration\/setchatmenuactions(_:)"]}],"abstract":[{"text":"Set the ","type":"text"},{"type":"codeVoice","code":"ChatMenuAction"},{"text":"s that will be available to the user.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"]]},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"abstract":[],"type":"topic","title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection","url":"\/documentation\/chatsdk"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"type":"topic","navigatorTitle":[{"text":"ChatConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"ChatConfiguration","abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"code":"ChatMenuAction","type":"codeVoice"},{"text":"s","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConfiguration","kind":"identifier"}],"url":"\/documentation\/chatsdk\/chatconfiguration","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/setChatMenuActions(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setChatMenuActions:"}],"role":"symbol","kind":"symbol","title":"setChatMenuActions(_:)","abstract":[{"type":"text","text":"Set the "},{"code":"ChatMenuAction","type":"codeVoice"},{"type":"text","text":"s that will be available to the user."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setChatMenuActions","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/setChatMenuActions(_:)","url":"\/documentation\/chatsdk\/chatconfiguration\/setchatmenuactions(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"setChatMenuActions:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setChatMenuActions:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setChatMenuActions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"actions","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"ZDKChatConfiguration","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatConfiguration"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1setChatMenuActions(_:)\/title","op":"replace","value":"setChatMenuActions:"},{"value":[{"text":"- ","kind":"text"},{"text":"setChatMenuActions:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1setChatMenuActions(_:)\/fragments"}]}]}