{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatengine"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatEngine) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEngine"}]}]}],"kind":"symbol","abstract":[{"code":"ChatEngine","type":"codeVoice"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/configuration","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/id","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/onUpdate","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/transferOptionDescription"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing(_:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/onEvent(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/engine()"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Engine-Implementations","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Loggable-Implementations","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Observable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"metadata":{"externalID":"c:@M@ChatSDK@objc(cs)ZDKChatEngine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatEngine","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ChatSDK"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"title":"ChatEngine","role":"symbol","roleHeading":"Class"},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/16ChatProvidersSDK8LoggableP","doc:\/\/com.zendesk.ChatSDK\/12MessagingAPI6EngineP","doc:\/\/com.zendesk.ChatSDK\/12MessagingAPI10ObservableP","doc:\/\/com.zendesk.ChatSDK\/@M@MessagingAPI@objc(pl)ZDKEngine","doc:\/\/com.zendesk.ChatSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatSDK\/s8CopyableP","doc:\/\/com.zendesk.ChatSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatSDK\/SQ","doc:\/\/com.zendesk.ChatSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","abstract":[{"type":"codeVoice","code":"ChatEngine"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"role":"symbol","url":"\/documentation\/chatsdk\/chatengine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatEngine","kind":"identifier"}],"title":"ChatEngine","navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/id":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/id","url":"\/documentation\/chatsdk\/chatengine\/id","abstract":[{"type":"text","text":"Product Identifier"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"type":"topic","title":"id","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.zendesk.ChatSDK/16ChatProvidersSDK8LoggableP":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/16ChatProvidersSDK8LoggableP","title":"ChatProvidersSDK.Loggable","type":"unresolvable"},"doc://com.zendesk.ChatSDK/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.zendesk.ChatSDK\/s8CopyableP","type":"unresolvable"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/onUpdate":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":" : (","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI6UpdateO","text":"Update","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/onUpdate","url":"\/documentation\/chatsdk\/chatengine\/onupdate","title":"onUpdate","type":"topic","role":"symbol"},"doc://com.zendesk.ChatSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/Engine-Implementations":{"title":"Engine Implementations","url":"\/documentation\/chatsdk\/chatengine\/engine-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Engine-Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/Loggable-Implementations":{"type":"topic","title":"Loggable Implementations","url":"\/documentation\/chatsdk\/chatengine\/loggable-implementations","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Loggable-Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/transferOptionDescription":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/transferOptionDescription","role":"symbol","type":"topic","title":"transferOptionDescription","kind":"symbol","abstract":[{"text":"Information describing the ","type":"text"},{"type":"codeVoice","code":"Engine"}],"url":"\/documentation\/chatsdk\/chatengine\/transferoptiondescription","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transferOptionDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TransferOptionDescription","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKTransferOptionDescription","kind":"typeIdentifier"}]},"doc://com.zendesk.ChatSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ChatSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.ChatSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ChatSDK/12MessagingAPI10ObservableP":{"title":"MessagingAPI.Observable","identifier":"doc:\/\/com.zendesk.ChatSDK\/12MessagingAPI10ObservableP","type":"unresolvable"},"doc://com.zendesk.ChatSDK/@M@MessagingAPI@objc(pl)ZDKEngine":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/@M@MessagingAPI@objc(pl)ZDKEngine","title":"MessagingAPI.ZDKEngine","type":"unresolvable"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/isConversationOngoing(_:)":{"title":"isConversationOngoing(_:)","url":"\/documentation\/chatsdk\/chatengine\/isconversationongoing(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConversationOngoing"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing(_:)","abstract":[{"text":"Allows the Messaging SDK to see if there’s a conversation on-going.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isConversationOngoing:"}],"kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/onEvent(_:)":{"title":"onEvent(_:)","abstract":[{"text":"This method is called when the end-user omits an event.","type":"text"},{"text":" ","type":"text"},{"text":"The Chat engine will then decide how to handle this event.","type":"text"}],"role":"symbol","url":"\/documentation\/chatsdk\/chatengine\/onevent(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Event","preciseIdentifier":"s:12MessagingAPI5EventO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/onEvent(_:)","kind":"symbol"},"doc://com.zendesk.ChatSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SH","type":"unresolvable"},"doc://com.zendesk.ChatSDK/12MessagingAPI6EngineP":{"type":"unresolvable","title":"MessagingAPI.Engine","identifier":"doc:\/\/com.zendesk.ChatSDK\/12MessagingAPI6EngineP"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/Observable-Implementations":{"title":"Observable Implementations","url":"\/documentation\/chatsdk\/chatengine\/observable-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Observable-Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.zendesk.ChatSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatSDK\/objc(pl)NSObject"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/configuration":{"title":"configuration","url":"\/documentation\/chatsdk\/chatengine\/configuration","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration","kind":"typeIdentifier","text":"ChatConfiguration"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/configuration","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"kind":"symbol"},"doc://com.zendesk.ChatSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ChatSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/engine()":{"url":"\/documentation\/chatsdk\/chatengine\/engine()","abstract":[{"type":"text","text":"Initialize the ChatEngine"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/engine()","title":"engine()","navigatorTitle":[{"kind":"identifier","text":"engineAndReturnError:"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"engine"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatEngine","text":"ChatEngine"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKChatEngine","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKChatEngine"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKChatEngine","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/configuration","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/id"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing(_:)"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/engine()"],"anchor":"Type-Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Engine-Implementations"],"anchor":"Default-Implementations"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKChatEngine"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKChatEngine","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title"},{"value":[{"kind":"identifier","text":"ZDKChatEngine"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatEngine"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1id\/title","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1id\/fragments","value":[{"kind":"identifier","text":"id"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1isConversationOngoing(_:)\/title","value":"isConversationOngoing:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1isConversationOngoing(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isConversationOngoing:"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1configuration\/title","op":"replace","value":"configuration"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1configuration\/fragments","op":"replace","value":[{"text":"configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1engine()\/title","op":"replace","value":"engineAndReturnError:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1engine()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"engineAndReturnError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}