{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This can be passed into the "},{"type":"codeVoice","code":"Messaging.buildUI(engines:configs:)"},{"type":"text","text":" method."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatsdk\/chatconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/chatconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","doc:\/\/com.zendesk.ChatSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatSDK\/SQ","doc:\/\/com.zendesk.ChatSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConfiguration"}],"title":"ChatConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration","modules":[{"name":"ChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChatConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/chatMenuActions","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/debugDescription","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/description","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isAgentAvailabilityEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isChatTranscriptPromptEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isOfflineFormEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isPreChatFormEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/menuActions","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/preChatFormConfiguration"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isEqual(_:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/setChatMenuActions(_:)"]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/isequal(_:)"},"doc://com.zendesk.ChatSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SQ"},"doc://com.zendesk.ChatSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isChatTranscriptPromptEnabled":{"role":"symbol","title":"isChatTranscriptPromptEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatTranscriptPromptEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If TRUE, users are asked if they want to request a chat transcript at the end of the chat. TRUE by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isChatTranscriptPromptEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isChatTranscriptPromptEnabled"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/ischattranscriptpromptenabled"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/preChatFormConfiguration":{"role":"symbol","title":"preChatFormConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatFormConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatFormConfiguration","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration"}],"abstract":[{"type":"text","text":"Configures the fields in the prechat form"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/preChatFormConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preChatFormConfiguration"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/prechatformconfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/chatMenuActions":{"role":"symbol","title":"chatMenuActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatMenuActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatMenuAction","preciseIdentifier":"c:@M@ChatSDK@E@ZDKChatMenuAction"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The list of Chat actions that the visitor can carry-out"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/chatMenuActions","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk\/chatconfiguration\/chatmenuactions"},"doc://com.zendesk.ChatSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatSDK\/objc(pl)NSObject"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/init()"},"doc://com.zendesk.ChatSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ChatSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isOfflineFormEnabled":{"role":"symbol","title":"isOfflineFormEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineFormEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If TRUE, the offline form will be shown to the user. TRUE by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isOfflineFormEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOfflineFormEnabled"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/isofflineformenabled"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isAgentAvailabilityEnabled":{"role":"symbol","title":"isAgentAvailabilityEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAgentAvailabilityEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If TRUE, Offline message will be shown to the user in case no agent is available. TRUE by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isAgentAvailabilityEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAgentAvailabilityEnabled"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/isagentavailabilityenabled"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isPreChatFormEnabled":{"role":"symbol","title":"isPreChatFormEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreChatFormEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If TRUE, the pre-chat form will be shown to the user. TRUE by default."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isPreChatFormEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPreChatFormEnabled"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/isprechatformenabled"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"role":"symbol","title":"ChatConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConfiguration"}],"abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConfiguration"}],"url":"\/documentation\/chatsdk\/chatconfiguration"},"doc://com.zendesk.ChatSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/description"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","title":"ChatSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/setChatMenuActions(_:)":{"role":"symbol","title":"setChatMenuActions(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setChatMenuActions"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Set the "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s that will be available to the user."}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/setChatMenuActions(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setChatMenuActions:"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/setchatmenuactions(_:)"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/menuActions":{"role":"symbol","title":"menuActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"menuActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Retrieve the Integer values of the "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s applied to the config"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/menuActions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"menuActions"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/menuactions"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/debugDescription":{"role":"symbol","title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/debugDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/debugdescription"},"doc://com.zendesk.ChatSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SH"},"doc://com.zendesk.ChatSDK/@M@SDKConfigurations@objc(pl)ZDKConfiguration":{"type":"unresolvable","title":"ZDKConfiguration","identifier":"doc:\/\/com.zendesk.ChatSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration"},"doc://com.zendesk.ChatSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ChatSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/debugDescription","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/description","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isAgentAvailabilityEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isChatTranscriptPromptEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isOfflineFormEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isPreChatFormEnabled","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/menuActions","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/preChatFormConfiguration"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/init()","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isEqual(_:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/setChatMenuActions(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKChatConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isChatTranscriptPromptEnabled\/title","value":"isChatTranscriptPromptEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isChatTranscriptPromptEnabled\/fragments","value":[{"kind":"identifier","text":"isChatTranscriptPromptEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1preChatFormConfiguration\/title","value":"preChatFormConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1preChatFormConfiguration\/fragments","value":[{"kind":"identifier","text":"preChatFormConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isOfflineFormEnabled\/title","value":"isOfflineFormEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isOfflineFormEnabled\/fragments","value":[{"kind":"identifier","text":"isOfflineFormEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isAgentAvailabilityEnabled\/title","value":"isAgentAvailabilityEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isAgentAvailabilityEnabled\/fragments","value":[{"kind":"identifier","text":"isAgentAvailabilityEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isPreChatFormEnabled\/title","value":"isPreChatFormEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isPreChatFormEnabled\/fragments","value":[{"kind":"identifier","text":"isPreChatFormEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title","value":"ZDKChatConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1setChatMenuActions(_:)\/title","value":"setChatMenuActions:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1setChatMenuActions(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setChatMenuActions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1menuActions\/title","value":"menuActions"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1menuActions\/fragments","value":[{"kind":"identifier","text":"menuActions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1debugDescription\/title","value":"debugDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1debugDescription\/fragments","value":[{"kind":"identifier","text":"debugDescription"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}