{"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/preChatFormConfiguration","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","modules":[{"name":"ChatSDK"}],"role":"symbol","roleHeading":"Instance Property","title":"preChatFormConfiguration","navigatorTitle":[{"text":"preChatFormConfiguration","kind":"identifier"}],"externalID":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration(py)preChatFormConfiguration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatFormConfiguration"},{"text":": ","kind":"text"},{"text":"ChatFormConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration"}]},"variants":[{"paths":["\/documentation\/chatsdk\/chatconfiguration\/prechatformconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatconfiguration\/prechatformconfiguration"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"Configures the fields in the prechat form","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatFormConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration","kind":"typeIdentifier","text":"ChatFormConfiguration"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"url":"\/documentation\/chatsdk\/chatformconfiguration","role":"symbol","abstract":[{"text":"Configuration object used to gather the desired requirements for a Chat form.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatFormConfiguration","kind":"identifier"}],"title":"ChatFormConfiguration","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"abstract":[{"text":"Configuration class to modify the behaviour of the Chat UI such as forms, and ","type":"text"},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","kind":"symbol","url":"\/documentation\/chatsdk\/chatconfiguration","title":"ChatConfiguration","role":"symbol","navigatorTitle":[{"text":"ChatConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConfiguration","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/preChatFormConfiguration":{"navigatorTitle":[{"text":"preChatFormConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configures the fields in the prechat form"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preChatFormConfiguration"},{"text":": ","kind":"text"},{"text":"ChatFormConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration"}],"url":"\/documentation\/chatsdk\/chatconfiguration\/prechatformconfiguration","type":"topic","role":"symbol","title":"preChatFormConfiguration","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/preChatFormConfiguration","kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"abstract":[],"type":"topic","title":"ChatSDK","url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"preChatFormConfiguration","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"preChatFormConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration","text":"ZDKChatFormConfiguration","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"},{"text":" * ","kind":"text"},{"text":"preChatFormConfiguration","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title","value":"ZDKChatFormConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title","value":"ZDKChatConfiguration","op":"replace"},{"value":[{"text":"ZDKChatConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1preChatFormConfiguration\/title","op":"replace","value":"preChatFormConfiguration"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1preChatFormConfiguration\/fragments","value":[{"kind":"identifier","text":"preChatFormConfiguration"}],"op":"replace"}]}]}