{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/emailTranscript","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/endChat"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/Equatable-Implementations","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKChatMenuAction) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMenuAction","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ChatMenuAction"}],"modules":[{"name":"ChatSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMenuAction"}],"title":"ChatMenuAction","role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@ChatSDK@E@ZDKChatMenuAction","symbolKind":"enum"},"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Possible items that appear in the right "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" in the Chat screen’s "},{"code":"UINavigationController","type":"codeVoice"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ChatSDK\/SQ","doc:\/\/com.zendesk.ChatSDK\/SH","doc:\/\/com.zendesk.ChatSDK\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatmenuaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatmenuaction"]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/endChat":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/endChat","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endChat"}],"title":"ChatMenuAction.endChat","navigatorTitle":[{"text":"ZDKChatMenuActionEndChat","kind":"identifier"}],"url":"\/documentation\/chatsdk\/chatmenuaction\/endchat","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Allows the user to end the chat","type":"text"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.ChatSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SY","type":"unresolvable"},"doc://com.zendesk.ChatSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SH","type":"unresolvable"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMenuAction"}],"role":"symbol","title":"ChatMenuAction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMenuAction"}],"abstract":[{"text":"Possible items that appear in the right ","type":"text"},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" in the Chat screen’s "},{"type":"codeVoice","code":"UINavigationController"}],"type":"topic","url":"\/documentation\/chatsdk\/chatmenuaction"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/Equatable-Implementations":{"url":"\/documentation\/chatsdk\/chatmenuaction\/equatable-implementations","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","kind":"article","abstract":[],"type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/chatsdk\/chatmenuaction\/init(rawvalue:)"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/RawRepresentable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/chatsdk\/chatmenuaction\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/emailTranscript":{"role":"symbol","url":"\/documentation\/chatsdk\/chatmenuaction\/emailtranscript","abstract":[{"type":"text","text":"Allows the user to send a transcript of the finished chat to the specified email"}],"kind":"symbol","title":"ChatMenuAction.emailTranscript","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emailTranscript"}],"navigatorTitle":[{"text":"ZDKChatMenuActionEmailTranscript","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/emailTranscript"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKChatMenuAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatMenuAction"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatMenuAction"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/emailTranscript","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/endChat"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKChatMenuAction"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKChatMenuActionEndChat","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1endChat\/title"},{"value":[{"text":"ZDKChatMenuActionEndChat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1endChat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/title","value":"ZDKChatMenuAction","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/fragments","value":[{"kind":"identifier","text":"ZDKChatMenuAction"}],"op":"replace"},{"value":"ZDKChatMenuActionEmailTranscript","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1emailTranscript\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1emailTranscript\/fragments","value":[{"text":"ZDKChatMenuActionEmailTranscript","kind":"identifier"}]}]}]}