{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatSDK\/SQ","doc:\/\/com.zendesk.ChatSDK\/SH","doc:\/\/com.zendesk.ChatSDK\/SY"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/formfieldstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/formfieldstatus"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKFormFieldStatus) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormFieldStatus"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"codeVoice","code":"FormFieldStatus"},{"type":"text","text":" is used to set if a field in the pre-chat or offline- form is"},{"type":"text","text":" "},{"code":"required","type":"codeVoice"},{"text":", ","type":"text"},{"code":"optional","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"hidden"},{"type":"text","text":"."}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hidden","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/optional","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/required"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/description"],"title":"Instance Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/Equatable-Implementations","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"},"metadata":{"title":"FormFieldStatus","modules":[{"name":"ChatSDK"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FormFieldStatus","kind":"identifier"}],"externalID":"c:@M@ChatSDK@E@ZDKFormFieldStatus","navigatorTitle":[{"text":"FormFieldStatus","kind":"identifier"}]},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/required":{"title":"FormFieldStatus.required","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/required","navigatorTitle":[{"text":"ZDKFormFieldStatusRequired","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatsdk\/formfieldstatus\/required","kind":"symbol","abstract":[{"type":"text","text":"Field will be shown to end-user with no "},{"type":"codeVoice","code":"skip"},{"text":" button.","type":"text"}]},"doc://com.zendesk.ChatSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SY"},"doc://com.zendesk.ChatSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SH"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/hidden":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hidden","title":"FormFieldStatus.hidden","type":"topic","role":"symbol","abstract":[{"text":"Field will not be shown to end-user.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidden"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFormFieldStatusHidden"}],"url":"\/documentation\/chatsdk\/formfieldstatus\/hidden"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"kind":"symbol","type":"topic","title":"FormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","role":"symbol","abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"type":"text","text":" is used to set if a field in the pre-chat or offline- form is"},{"type":"text","text":" "},{"type":"codeVoice","code":"required"},{"type":"text","text":", "},{"code":"optional","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"hidden"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormFieldStatus"}],"navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"url":"\/documentation\/chatsdk\/formfieldstatus"},"doc://com.zendesk.ChatSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatSDK\/SQ"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/description":{"url":"\/documentation\/chatsdk\/formfieldstatus\/description","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/init(rawValue:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/init(rawValue:)","url":"\/documentation\/chatsdk\/formfieldstatus\/init(rawvalue:)"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/optional":{"abstract":[{"type":"text","text":"Field will be shown to end-user with a "},{"type":"codeVoice","code":"skip"},{"text":" button.","type":"text"}],"url":"\/documentation\/chatsdk\/formfieldstatus\/optional","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"optional","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKFormFieldStatusOptional","kind":"identifier"}],"type":"topic","title":"FormFieldStatus.optional","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/optional"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/RawRepresentable-Implementations":{"abstract":[],"type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/chatsdk\/formfieldstatus\/rawrepresentable-implementations","kind":"article"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/Equatable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/chatsdk\/formfieldstatus\/equatable-implementations","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKFormFieldStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hidden","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/optional","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/required"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKFormFieldStatus"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1required\/title","value":"ZDKFormFieldStatusRequired","op":"replace"},{"value":[{"text":"ZDKFormFieldStatusRequired","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1required\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1hidden\/title","value":"ZDKFormFieldStatusHidden"},{"value":[{"text":"ZDKFormFieldStatusHidden","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1hidden\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title","op":"replace","value":"ZDKFormFieldStatus"},{"value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1optional\/title","value":"ZDKFormFieldStatusOptional"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFormFieldStatusOptional"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1optional\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}