{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Engine-Implementations"]]},"metadata":{"externalID":"c:@CM@ChatSDK@objc(cs)ZDKChatEngine(im)isConversationOngoing","modules":[{"name":"ChatSDK"}],"platforms":[],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isConversationOngoing","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","title":"isConversationOngoing()","navigatorTitle":[{"kind":"identifier","text":"isConversationOngoing"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine\/isconversationongoing()"]},{"paths":["\/documentation\/chatsdk\/chatengine\/isconversationongoing()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isConversationOngoing","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Engine.isConversationOngoing()"},{"text":".","type":"text"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use isConversationOngoing(_ completion: @escaping (Bool) -> Void) instead"}],"type":"paragraph"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/Engine-Implementations":{"role":"collectionGroup","url":"\/documentation\/chatsdk\/chatengine\/engine-implementations","kind":"article","abstract":[],"title":"Engine Implementations","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Engine-Implementations","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"role":"symbol","url":"\/documentation\/chatsdk\/chatengine","navigatorTitle":[{"kind":"identifier","text":"ChatEngine"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","kind":"symbol","title":"ChatEngine","type":"topic","abstract":[{"type":"codeVoice","code":"ChatEngine"},{"type":"text","text":" is the access point for the UI of the Chat SDK. It is the ChatEngine."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatEngine"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/isConversationOngoing()":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing()","role":"symbol","deprecated":true,"kind":"symbol","title":"isConversationOngoing()","type":"topic","url":"\/documentation\/chatsdk\/chatengine\/isconversationongoing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isConversationOngoing","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isConversationOngoing","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isConversationOngoing","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isConversationOngoing","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isConversationOngoing","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title","value":"ZDKChatEngine","op":"replace"},{"op":"replace","value":[{"text":"ZDKChatEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments"},{"op":"replace","value":"isConversationOngoing","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1isConversationOngoing()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1isConversationOngoing()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isConversationOngoing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}