{"variants":[{"paths":["\/documentation\/chatsdk\/chatmenuaction\/endchat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatmenuaction\/endchat"]}],"metadata":{"modules":[{"name":"ChatSDK"}],"navigatorTitle":[{"text":"ZDKChatMenuActionEndChat","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"endChat","kind":"identifier"}],"externalID":"c:@M@ChatSDK@E@ZDKChatMenuAction@ZDKChatMenuActionEndChat","symbolKind":"case","title":"ChatMenuAction.endChat","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction"]]},"abstract":[{"text":"Allows the user to end the chat","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"endChat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/endChat","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction/endChat":{"abstract":[{"text":"Allows the user to end the chat","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"endChat","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction\/endChat","navigatorTitle":[{"kind":"identifier","text":"ZDKChatMenuActionEndChat"}],"role":"symbol","title":"ChatMenuAction.endChat","url":"\/documentation\/chatsdk\/chatmenuaction\/endchat"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection","type":"topic","abstract":[],"title":"ChatSDK","url":"\/documentation\/chatsdk"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMenuAction"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Possible items that appear in the right "},{"code":"UIBarButtonItem","type":"codeVoice"},{"text":" in the Chat screen’s ","type":"text"},{"type":"codeVoice","code":"UINavigationController"}],"url":"\/documentation\/chatsdk\/chatmenuaction","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMenuAction"}],"title":"ChatMenuAction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKChatMenuActionEndChat","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKChatMenuActionEndChat","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKChatMenuActionEndChat"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1endChat\/title","op":"replace","value":"ZDKChatMenuActionEndChat"},{"value":[{"text":"ZDKChatMenuActionEndChat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction~1endChat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/title","value":"ZDKChatMenuAction"},{"value":[{"text":"ZDKChatMenuAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/fragments"}]}]}