{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"abstract":[{"type":"text","text":"Product Identifier"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/id","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ChatSDK"}],"title":"id","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatEngine(py)id"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatengine\/id"]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/id":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/id","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","abstract":[{"text":"Product Identifier","type":"text"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"url":"\/documentation\/chatsdk\/chatengine\/id","kind":"symbol","title":"id"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"kind":"symbol","title":"ChatEngine","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEngine"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"url":"\/documentation\/chatsdk\/chatengine","abstract":[{"type":"codeVoice","code":"ChatEngine"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"abstract":[],"type":"topic","title":"ChatSDK","url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"id"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"id","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1id\/title","op":"replace","value":"id"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title","value":"ZDKChatEngine"},{"value":[{"kind":"identifier","text":"ZDKChatEngine"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments"}]}]}