{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"ChatSDK"}],"externalID":"ChatSDK","title":"ChatSDK","roleHeading":"Framework","role":"collection","symbolKind":"module"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk"]},{"paths":["\/documentation\/chatsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"abstract":[],"type":"topic","title":"ChatSDK","url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatSDKVersionString":{"kind":"symbol","type":"topic","url":"\/documentation\/chatsdk\/chatsdkversionstring","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatSDKVersionString","title":"ChatSDKVersionString","abstract":[{"type":"text","text":"Project version string for ChatSDK."}],"fragments":[{"text":"ChatSDKVersionString","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"abstract":[{"text":"Configuration class to modify the behaviour of the Chat UI such as forms, and ","type":"text"},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","kind":"symbol","url":"\/documentation\/chatsdk\/chatconfiguration","title":"ChatConfiguration","role":"symbol","navigatorTitle":[{"text":"ChatConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConfiguration","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction":{"abstract":[{"type":"text","text":"Possible items that appear in the right "},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" in the Chat screen’s ","type":"text"},{"code":"UINavigationController","type":"codeVoice"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMenuAction","kind":"identifier"}],"title":"ChatMenuAction","navigatorTitle":[{"kind":"identifier","text":"ChatMenuAction"}],"url":"\/documentation\/chatsdk\/chatmenuaction"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"kind":"symbol","title":"ChatEngine","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEngine"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"url":"\/documentation\/chatsdk\/chatengine","abstract":[{"type":"codeVoice","code":"ChatEngine"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"url":"\/documentation\/chatsdk\/chatformconfiguration","role":"symbol","abstract":[{"text":"Configuration object used to gather the desired requirements for a Chat form.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatFormConfiguration","kind":"identifier"}],"title":"ChatFormConfiguration","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"abstract":[{"type":"codeVoice","code":"FormFieldStatus"},{"text":" is used to set if a field in the pre-chat or offline- form is","type":"text"},{"text":" ","type":"text"},{"code":"required","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"optional"},{"type":"text","text":" or "},{"code":"hidden","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FormFieldStatus","kind":"identifier"}],"type":"topic","title":"FormFieldStatus","navigatorTitle":[{"text":"FormFieldStatus","kind":"identifier"}],"url":"\/documentation\/chatsdk\/formfieldstatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","role":"symbol","kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatSDKVersionNumber":{"url":"\/documentation\/chatsdk\/chatsdkversionnumber","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatSDKVersionNumber","title":"ChatSDKVersionNumber","kind":"symbol","abstract":[{"type":"text","text":"Project version number for ChatSDK."}],"type":"topic","fragments":[{"kind":"identifier","text":"ChatSDKVersionNumber"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"],"title":"Classes"},{"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatSDKVersionNumber","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatSDKVersionString"],"title":"Variables"},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"ZDKChatConfiguration","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","value":[{"text":"ZDKChatConfiguration","kind":"identifier"}]},{"op":"replace","value":"ZDKChatMenuAction","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/title"},{"value":[{"text":"ZDKChatMenuAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/fragments","op":"replace"},{"op":"replace","value":"ZDKChatEngine","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title"},{"value":[{"text":"ZDKChatEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments","op":"replace"},{"op":"replace","value":"ZDKChatFormConfiguration","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title"},{"value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments"},{"op":"replace","value":"ZDKFormFieldStatus","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title"},{"value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments","op":"replace"}]}]}