{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/description"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration(py)description","modules":[{"name":"ChatSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/description","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"url":"\/documentation\/chatsdk\/chatformconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatFormConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration object used to gather the desired requirements for a Chat form.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","title":"ChatFormConfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/description":{"url":"\/documentation\/chatsdk\/chatformconfiguration\/description","title":"description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/description"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKChatFormConfiguration","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title"},{"value":[{"text":"ZDKChatFormConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1description\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}