{"variants":[{"paths":["\/documentation\/chatsdk\/chatformconfiguration\/email"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/chatformconfiguration\/email"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Sets how the email field is presented to the end-user. Field is ","type":"text"},{"code":".optional","type":"codeVoice"},{"text":" by default.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/email","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"text":"FormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]]},"kind":"symbol","sections":[],"metadata":{"title":"email","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration(py)email","roleHeading":"Instance Property","navigatorTitle":[{"text":"email","kind":"identifier"}],"modules":[{"name":"ChatSDK"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormFieldStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}]},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","url":"\/documentation\/chatsdk\/formfieldstatus","abstract":[{"type":"codeVoice","code":"FormFieldStatus"},{"type":"text","text":" is used to set if a field in the pre-chat or offline- form is"},{"type":"text","text":" "},{"type":"codeVoice","code":"required"},{"type":"text","text":", "},{"type":"codeVoice","code":"optional"},{"type":"text","text":" or "},{"type":"codeVoice","code":"hidden"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"FormFieldStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormFieldStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"FormFieldStatus"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/email":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/email","kind":"symbol","type":"topic","title":"email","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormFieldStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"}],"navigatorTitle":[{"text":"email","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets how the email field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"role":"symbol","url":"\/documentation\/chatsdk\/chatformconfiguration\/email"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"url":"\/documentation\/chatsdk\/chatformconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatFormConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration object used to gather the desired requirements for a Chat form.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","title":"ChatFormConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"email","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"email"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKFormFieldStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKFormFieldStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title"},{"value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments"},{"value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/navigatorTitle"},{"value":"email","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1email\/title"},{"value":[{"text":"email","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1email\/fragments"},{"value":"ZDKChatFormConfiguration","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title"},{"value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/navigatorTitle"}]}]}