{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"metadata":{"role":"collectionGroup","modules":[{"name":"ChatSDK"}],"title":"Engine Implementations"},"variants":[{"paths":["\/documentation\/chatsdk\/chatengine\/engine-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatengine\/engine-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/Engine-Implementations"},"sections":[],"kind":"article","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing()","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/observeUpdates(_:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/start(messagingAPI:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/stop()"],"generated":true}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/observeUpdates(_:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/observeUpdates(_:)","abstract":[{"text":"Allows Messaging SDK to listen to updates emitted bytthe Chat Engine","type":"text"}],"url":"\/documentation\/chatsdk\/chatengine\/observeupdates(_:)","kind":"symbol","title":"observeUpdates(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"observeUpdates","kind":"identifier"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6UpdateO","text":"Update"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> MessagingAPI","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken","text":"ObservationToken"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/start(messagingAPI:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/start(messagingAPI:)","abstract":[{"text":"Notifies the engine to start taking over the support process.","type":"text"}],"url":"\/documentation\/chatsdk\/chatengine\/start(messagingapi:)","kind":"symbol","title":"start(messagingAPI:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"messagingAPI","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI0A11APIProtocolP","text":"MessagingAPIProtocol"},{"kind":"text","text":")"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/stop()":{"abstract":[{"type":"text","text":"MessagingSDK calls this when the current session ends."}],"url":"\/documentation\/chatsdk\/chatengine\/stop()","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/stop()","title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/isConversationOngoing()":{"deprecated":true,"kind":"symbol","title":"isConversationOngoing()","type":"topic","abstract":[],"url":"\/documentation\/chatsdk\/chatengine\/isconversationongoing()","navigatorTitle":[{"text":"isConversationOngoing","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isConversationOngoing"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection","type":"topic","abstract":[],"title":"ChatSDK","url":"\/documentation\/chatsdk"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatEngine","kind":"identifier"}],"title":"ChatEngine","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","navigatorTitle":[{"kind":"identifier","text":"ChatEngine"}],"abstract":[{"code":"ChatEngine","type":"codeVoice"},{"type":"text","text":" is the access point for the UI of the Chat SDK. It is the ChatEngine."}],"url":"\/documentation\/chatsdk\/chatengine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/isConversationOngoing()","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/observeUpdates(_:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/start(messagingAPI:)","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/stop()"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1isConversationOngoing()\/title","value":"isConversationOngoing","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isConversationOngoing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1isConversationOngoing()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title","value":"ZDKChatEngine"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatEngine"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments"}]}]}