{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"department","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"FormFieldStatus","kind":"typeIdentifier"}],"title":"department","symbolKind":"property","role":"symbol","modules":[{"name":"ChatSDK"}],"navigatorTitle":[{"text":"department","kind":"identifier"}],"externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration(py)department","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"department"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/department"},"sections":[],"abstract":[{"type":"text","text":"Sets how the department selection field is presented to the end-user. Field is "},{"code":".optional","type":"codeVoice"},{"type":"text","text":" by default."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/department"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/department"]}],"kind":"symbol","references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"kind":"symbol","type":"topic","title":"FormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","role":"symbol","abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"type":"text","text":" is used to set if a field in the pre-chat or offline- form is"},{"type":"text","text":" "},{"type":"codeVoice","code":"required"},{"type":"text","text":", "},{"code":"optional","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"hidden"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormFieldStatus"}],"navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"url":"\/documentation\/chatsdk\/formfieldstatus"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/department":{"url":"\/documentation\/chatsdk\/chatformconfiguration\/department","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/department","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"department"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"FormFieldStatus","kind":"typeIdentifier"}],"abstract":[{"text":"Sets how the department selection field is presented to the end-user. Field is ","type":"text"},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"role":"symbol","navigatorTitle":[{"text":"department","kind":"identifier"}],"type":"topic","title":"department"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"title":"ChatFormConfiguration","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration object used to gather the desired requirements for a Chat form."}],"url":"\/documentation\/chatsdk\/chatformconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatFormConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"department","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"department","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ZDKFormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"},{"text":" ","kind":"text"},{"kind":"identifier","text":"department"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title","value":"ZDKFormFieldStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments","value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1department\/title","op":"replace","value":"department"},{"value":[{"text":"department","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1department\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title","value":"ZDKChatFormConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments","value":[{"text":"ZDKChatFormConfiguration","kind":"identifier"}]}]}]}