{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/init(name:email:phoneNumber:department:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithName:email:phoneNumber:department:"}],"role":"symbol","title":"init(name:email:phoneNumber:department:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"FormFieldStatus"},{"kind":"text","text":", "},{"text":"phoneNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FormFieldStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":", "},{"text":"department","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"FormFieldStatus"},{"text":")","kind":"text"}],"externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration(im)initWithName:email:phoneNumber:department:","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"ChatSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","text":"FormFieldStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"text":" = .optional, ","kind":"text"},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":" = .optional, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","text":"FormFieldStatus"},{"kind":"text","text":" = .optional, "},{"kind":"externalParam","text":"department"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"FormFieldStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"},{"kind":"text","text":" = .optional)"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]]},"variants":[{"paths":["\/documentation\/chatsdk\/chatformconfiguration\/init(name:email:phonenumber:department:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/init(name:email:phonenumber:department:)"]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"title":"ChatFormConfiguration","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration object used to gather the desired requirements for a Chat form."}],"url":"\/documentation\/chatsdk\/chatformconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatFormConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/init(name:email:phoneNumber:department:)":{"abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"FormFieldStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"email"},{"text":": ","kind":"text"},{"text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"phoneNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":", "},{"text":"department","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FormFieldStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/chatsdk\/chatformconfiguration\/init(name:email:phonenumber:department:)","title":"init(name:email:phoneNumber:department:)","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/init(name:email:phoneNumber:department:)","navigatorTitle":[{"text":"initWithName:email:phoneNumber:department:","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"kind":"symbol","type":"topic","title":"FormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","role":"symbol","abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"type":"text","text":" is used to set if a field in the pre-chat or offline- form is"},{"type":"text","text":" "},{"type":"codeVoice","code":"required"},{"type":"text","text":", "},{"code":"optional","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"hidden"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormFieldStatus"}],"navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"url":"\/documentation\/chatsdk\/formfieldstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithName:email:phoneNumber:department:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:email:phoneNumber:department:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","text":"ZDKFormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"text":"email:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKFormFieldStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus"},{"kind":"text","text":") "},{"text":"email","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"phoneNumber:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"phoneNumber","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"department:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","kind":"typeIdentifier","text":"ZDKFormFieldStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"department"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title","value":"ZDKChatFormConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}],"op":"replace"},{"value":"initWithName:email:phoneNumber:department:","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1init(name:email:phoneNumber:department:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithName:email:phoneNumber:department:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1init(name:email:phoneNumber:department:)\/fragments"},{"op":"replace","value":"ZDKFormFieldStatus","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title"},{"value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}