{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/name"]},{"paths":["\/documentation\/chatsdk\/chatformconfiguration\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Sets how the name field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"type":"text","text":" by default."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/name","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"name"}],"roleHeading":"Instance Property","title":"name","role":"symbol","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration(py)name","modules":[{"name":"ChatSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","text":"FormFieldStatus"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","kind":"typeIdentifier"}]}]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"title":"ChatFormConfiguration","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration object used to gather the desired requirements for a Chat form."}],"url":"\/documentation\/chatsdk\/chatformconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatFormConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ChatFormConfiguration","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/name":{"abstract":[{"type":"text","text":"Sets how the name field is presented to the end-user. Field is "},{"type":"codeVoice","code":".optional"},{"text":" by default.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","kind":"typeIdentifier","text":"FormFieldStatus"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/name","kind":"symbol","title":"name","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/name","navigatorTitle":[{"text":"name","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"kind":"symbol","type":"topic","title":"FormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","role":"symbol","abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"type":"text","text":" is used to set if a field in the pre-chat or offline- form is"},{"type":"text","text":" "},{"type":"codeVoice","code":"required"},{"type":"text","text":", "},{"code":"optional","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"hidden"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormFieldStatus"}],"navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"url":"\/documentation\/chatsdk\/formfieldstatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"name"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"name","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKFormFieldStatus","preciseIdentifier":"c:@M@ChatSDK@E@ZDKFormFieldStatus","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title","value":"ZDKChatFormConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatFormConfiguration"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1name\/title","value":"name","op":"replace"},{"op":"replace","value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1name\/fragments"},{"value":"ZDKFormFieldStatus","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments","value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}]}]}]}