{"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/configuration","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"externalID":"c:@M@ChatSDK@objc(cs)ZDKChatEngine(py)configuration","title":"configuration","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine\/configuration"]},{"paths":["\/documentation\/chatsdk\/chatengine\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"title":"ChatConfiguration","url":"\/documentation\/chatsdk\/chatconfiguration","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","role":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"url":"\/documentation\/chatsdk\/chatengine","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","role":"symbol","abstract":[{"code":"ChatEngine","type":"codeVoice"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"title":"ChatEngine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatEngine","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatEngine"}],"kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/configuration":{"url":"\/documentation\/chatsdk\/chatengine\/configuration","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/configuration","role":"symbol","abstract":[],"title":"configuration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"text":"ChatConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"type":"topic","title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"configuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"configuration"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ZDKChatConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration"},{"kind":"text","text":" * "},{"text":"configuration","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title","value":"ZDKChatConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title","value":"ZDKChatEngine","op":"replace"},{"op":"replace","value":[{"text":"ZDKChatEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1configuration\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1configuration\/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"}]}]}