{"abstract":[{"type":"text","text":"The list of Chat actions that the visitor can carry-out"}],"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"s:7ChatSDK0A13ConfigurationC15chatMenuActionsSayAA0aE6ActionOGvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatMenuActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatMenuAction","preciseIdentifier":"c:@M@ChatSDK@E@ZDKChatMenuAction"},{"kind":"text","text":"]"}],"modules":[{"name":"ChatSDK"}],"title":"chatMenuActions","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatMenuActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","preciseIdentifier":"c:@M@ChatSDK@E@ZDKChatMenuAction","text":"ChatMenuAction"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/chatMenuActions"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"]]},"variants":[{"paths":["\/documentation\/chatsdk\/chatconfiguration\/chatmenuactions"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatMenuAction":{"type":"topic","title":"ChatMenuAction","url":"\/documentation\/chatsdk\/chatmenuaction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMenuAction"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMenuAction"}],"abstract":[{"type":"text","text":"Possible items that appear in the right "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" in the Chat screen’s "},{"type":"codeVoice","code":"UINavigationController"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatMenuAction","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/chatMenuActions":{"title":"chatMenuActions","abstract":[{"type":"text","text":"The list of Chat actions that the visitor can carry-out"}],"role":"symbol","url":"\/documentation\/chatsdk\/chatconfiguration\/chatmenuactions","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatMenuActions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ChatMenuAction","preciseIdentifier":"c:@M@ChatSDK@E@ZDKChatMenuAction","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/chatMenuActions","kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"title":"ChatConfiguration","navigatorTitle":[{"text":"ChatConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration class to modify the behaviour of the Chat UI such as forms, and "},{"code":"ChatMenuAction","type":"codeVoice"},{"type":"text","text":"s"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","type":"topic","url":"\/documentation\/chatsdk\/chatconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/title","value":"ZDKChatMenuAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/fragments","value":[{"kind":"identifier","text":"ZDKChatMenuAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatMenuAction\/navigatorTitle","value":[{"text":"ZDKChatMenuAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title","value":"ZDKChatConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","value":[{"text":"ZDKChatConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatConfiguration"}]}]}]}