{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"roleHeading":"Instance Property","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatFormConfiguration(py)debugDescription","title":"debugDescription","modules":[{"name":"ChatSDK"}],"role":"symbol","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/debugDescription"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/chatsdk\/chatformconfiguration\/debugdescription"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/chatformconfiguration\/debugdescription"]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration":{"type":"topic","url":"\/documentation\/chatsdk\/chatformconfiguration","abstract":[{"text":"Configuration object used to gather the desired requirements for a Chat form.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatFormConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"ChatFormConfiguration"}],"title":"ChatFormConfiguration"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"abstract":[],"type":"topic","title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","role":"collection","url":"\/documentation\/chatsdk"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatFormConfiguration/debugDescription":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"url":"\/documentation\/chatsdk\/chatformconfiguration\/debugdescription","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatFormConfiguration\/debugDescription","kind":"symbol","title":"debugDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"debugDescription","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"debugDescription","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"debugDescription"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/title","value":"ZDKChatFormConfiguration"},{"value":[{"text":"ZDKChatFormConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration\/fragments","op":"replace"},{"op":"replace","value":"debugDescription","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1debugDescription\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatFormConfiguration~1debugDescription\/fragments","op":"replace","value":[{"text":"debugDescription","kind":"identifier"}]}]}]}