{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAgentAvailabilityEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"If TRUE, Offline message will be shown to the user in case no agent is available. TRUE by default.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"externalID":"c:@M@ChatSDK@objc(cs)ZDKChatConfiguration(py)isAgentAvailabilityEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAgentAvailabilityEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"ChatSDK"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isAgentAvailabilityEnabled"}],"roleHeading":"Instance Property","title":"isAgentAvailabilityEnabled"},"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isAgentAvailabilityEnabled","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chatsdk\/chatconfiguration\/isagentavailabilityenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/chatconfiguration\/isagentavailabilityenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration/isAgentAvailabilityEnabled":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration\/isAgentAvailabilityEnabled","type":"topic","kind":"symbol","title":"isAgentAvailabilityEnabled","role":"symbol","url":"\/documentation\/chatsdk\/chatconfiguration\/isagentavailabilityenabled","abstract":[{"type":"text","text":"If TRUE, Offline message will be shown to the user in case no agent is available. TRUE by default."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAgentAvailabilityEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isAgentAvailabilityEnabled","kind":"identifier"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"role":"collection","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","url":"\/documentation\/chatsdk","title":"ChatSDK","abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatConfiguration":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatConfiguration","title":"ChatConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatConfiguration"}],"abstract":[{"text":"Configuration class to modify the behaviour of the Chat UI such as forms, and ","type":"text"},{"type":"codeVoice","code":"ChatMenuAction"},{"type":"text","text":"s"}],"url":"\/documentation\/chatsdk\/chatconfiguration","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"isAgentAvailabilityEnabled"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isAgentAvailabilityEnabled","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"isAgentAvailabilityEnabled","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isAgentAvailabilityEnabled\/title","value":"isAgentAvailabilityEnabled","op":"replace"},{"value":[{"kind":"identifier","text":"isAgentAvailabilityEnabled"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration~1isAgentAvailabilityEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/title","value":"ZDKChatConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatConfiguration"}]}]}]}