{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hidden"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"]]},"abstract":[{"type":"text","text":"Field will not be shown to end-user."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/formfieldstatus\/hidden"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatsdk\/formfieldstatus\/hidden"]}],"metadata":{"role":"symbol","externalID":"c:@M@ChatSDK@E@ZDKFormFieldStatus@ZDKFormFieldStatusHidden","navigatorTitle":[{"kind":"identifier","text":"ZDKFormFieldStatusHidden"}],"modules":[{"name":"ChatSDK"}],"title":"FormFieldStatus.hidden","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}]},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","title":"FormFieldStatus","url":"\/documentation\/chatsdk\/formfieldstatus","navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFieldStatus"}],"abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"text":" is used to set if a field in the pre-chat or offline- form is","type":"text"},{"text":" ","type":"text"},{"code":"required","type":"codeVoice"},{"text":", ","type":"text"},{"code":"optional","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"hidden","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/hidden":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"type":"topic","url":"\/documentation\/chatsdk\/formfieldstatus\/hidden","title":"FormFieldStatus.hidden","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKFormFieldStatusHidden"}],"abstract":[{"type":"text","text":"Field will not be shown to end-user."}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKFormFieldStatusHidden","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFormFieldStatusHidden"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKFormFieldStatusHidden"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKFormFieldStatus","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title"},{"op":"replace","value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments"},{"op":"replace","value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/navigatorTitle"},{"op":"replace","value":"ZDKFormFieldStatusHidden","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1hidden\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFormFieldStatusHidden"}],"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1hidden\/fragments"}]}]}