{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/optional"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optional"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"]]},"variants":[{"paths":["\/documentation\/chatsdk\/formfieldstatus\/optional"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/formfieldstatus\/optional"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ChatSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKFormFieldStatusOptional"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optional","kind":"identifier"}],"title":"FormFieldStatus.optional","externalID":"c:@M@ChatSDK@E@ZDKFormFieldStatus@ZDKFormFieldStatusOptional","symbolKind":"case","roleHeading":"Case"},"abstract":[{"text":"Field will be shown to end-user with a ","type":"text"},{"code":"skip","type":"codeVoice"},{"text":" button.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/optional":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optional"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/optional","navigatorTitle":[{"kind":"identifier","text":"ZDKFormFieldStatusOptional"}],"kind":"symbol","url":"\/documentation\/chatsdk\/formfieldstatus\/optional","abstract":[{"text":"Field will be shown to end-user with a ","type":"text"},{"code":"skip","type":"codeVoice"},{"text":" button.","type":"text"}],"type":"topic","role":"symbol","title":"FormFieldStatus.optional"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","title":"FormFieldStatus","url":"\/documentation\/chatsdk\/formfieldstatus","navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFieldStatus"}],"abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"text":" is used to set if a field in the pre-chat or offline- form is","type":"text"},{"text":" ","type":"text"},{"code":"required","type":"codeVoice"},{"text":", ","type":"text"},{"code":"optional","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"hidden","type":"codeVoice"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKFormFieldStatusOptional","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKFormFieldStatusOptional"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKFormFieldStatusOptional"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1optional\/title","op":"replace","value":"ZDKFormFieldStatusOptional"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus~1optional\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFormFieldStatusOptional"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title","op":"replace","value":"ZDKFormFieldStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/navigatorTitle","op":"replace","value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}]}]}]}