{"variants":[{"paths":["\/documentation\/chatsdk\/formfieldstatus\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus"]]},"metadata":{"role":"collectionGroup","title":"RawRepresentable Implementations","modules":[{"name":"ChatSDK"}],"roleHeading":"API Collection"},"sections":[],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hashValue"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hash(into:)"]}],"kind":"article","references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/hashValue":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hashValue","url":"\/documentation\/chatsdk\/formfieldstatus\/hashvalue","title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"role":"symbol","type":"topic"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"url":"\/documentation\/chatsdk","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","abstract":[],"kind":"symbol","type":"topic","title":"ChatSDK","role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus":{"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus","title":"FormFieldStatus","url":"\/documentation\/chatsdk\/formfieldstatus","navigatorTitle":[{"kind":"identifier","text":"FormFieldStatus"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormFieldStatus"}],"abstract":[{"code":"FormFieldStatus","type":"codeVoice"},{"text":" is used to set if a field in the pre-chat or offline- form is","type":"text"},{"text":" ","type":"text"},{"code":"required","type":"codeVoice"},{"text":", ","type":"text"},{"code":"optional","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"hidden","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/FormFieldStatus/hash(into:)":{"url":"\/documentation\/chatsdk\/formfieldstatus\/hash(into:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"title":"hash(into:)","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/FormFieldStatus\/hash(into:)","role":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]}}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/title","value":"ZDKFormFieldStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/fragments","value":[{"kind":"identifier","text":"ZDKFormFieldStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1FormFieldStatus\/navigatorTitle","value":[{"text":"ZDKFormFieldStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}