{"metadata":{"role":"symbol","roleHeading":"Type Method","title":"engine()","externalID":"c:@M@ChatSDK@objc(cs)ZDKChatEngine(cm)engineAndReturnError:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engine","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ChatEngine","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatEngine","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"engineAndReturnError:","kind":"identifier"}],"modules":[{"name":"ChatSDK"}],"symbolKind":"method"},"kind":"symbol","variants":[{"paths":["\/documentation\/chatsdk\/chatengine\/engine()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatsdk\/chatengine\/engine()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"abstract":[{"type":"text","text":"Initialize the ChatEngine"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/engine()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engine","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatEngine","text":"ChatEngine","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"ChatError.chatIsNotInitialized","type":"codeVoice"},{"type":"text","text":" error, if Chat was not previously initialized"}]}],"type":"aside","style":"note"}],"kind":"content"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/engine()":{"title":"engine()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/engine()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engine","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ChatEngine","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatEngine"}],"abstract":[{"type":"text","text":"Initialize the ChatEngine"}],"navigatorTitle":[{"text":"engineAndReturnError:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatsdk\/chatengine\/engine()"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"abstract":[{"type":"codeVoice","code":"ChatEngine"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","type":"topic","role":"symbol","title":"ChatEngine","url":"\/documentation\/chatsdk\/chatengine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatEngine","kind":"identifier"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"engineAndReturnError:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"engineAndReturnError:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ChatSDK@objc(cs)ZDKChatEngine","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","text":"ZDKChatEngine","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"engineAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"add","value":{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1engine()\/title","op":"replace","value":"engineAndReturnError:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine~1engine()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"engineAndReturnError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title","op":"replace","value":"ZDKChatEngine"},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatEngine"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/navigatorTitle","op":"replace","value":[{"text":"ZDKChatEngine","kind":"identifier"}]}]}]}