{"identifier":{"url":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/onUpdate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":" : (","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI6UpdateO","text":"Update","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Observable.onUpdate"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatsdk\/chatengine\/onupdate"]}],"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ChatSDK"}],"symbolKind":"property","externalID":"s:7ChatSDK0A6EngineC8onUpdateSDy12MessagingAPI20ObservableIdentifierOyAE0E0OcGvp","title":"onUpdate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"text":" : (","kind":"text"},{"text":"Update","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6UpdateO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":"]","kind":"text"}],"role":"symbol"},"kind":"symbol","references":{"doc://com.zendesk.ChatSDK/documentation/ChatSDK":{"title":"ChatSDK","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatsdk","abstract":[],"role":"collection"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine/onUpdate":{"title":"onUpdate","identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine\/onUpdate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":" : (","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI6UpdateO","text":"Update","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/chatsdk\/chatengine\/onupdate"},"doc://com.zendesk.ChatSDK/documentation/ChatSDK/ChatEngine":{"abstract":[{"type":"codeVoice","code":"ChatEngine"},{"text":" is the access point for the UI of the Chat SDK. It is the ChatEngine.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatSDK\/documentation\/ChatSDK\/ChatEngine","type":"topic","role":"symbol","title":"ChatEngine","url":"\/documentation\/chatsdk\/chatengine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatEngine","kind":"identifier"}],"navigatorTitle":[{"text":"ChatEngine","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKChatEngine","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/title"},{"value":[{"text":"ZDKChatEngine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/fragments"},{"value":[{"kind":"identifier","text":"ZDKChatEngine"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatSDK~1documentation~1ChatSDK~1ChatEngine\/navigatorTitle"}]}]}